server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:product-group-id}
      client-id: product-client-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: ${KAFKA_AUTO-OFFSET-RESET:earliest}
      fetch-min-size: 500
      fetch-max-wait: 900
      isolation-level: read_committed
      max-poll-records: 10
    bootstrap-servers: ${KAFKA_HOST:localhost:9094}
    product:
      topic: product-topic