spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 0
      client-id: producer-id
    properties:
      schema:
        registry:
          url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
      auto.register.schemas: false
      use.latest.version: true
    product:
      topic:
        name: product-topic
    payment:
      topic:
        name: payment-topic